### DISCUSSION TITLE
How to retrive the output of this action?

### DISCUSSION THREAD

**Discussion by orenzi-tr** [Azure/webapps-deploy#133] [Q&A]
Hi,
I'm trying to retrieve the output of this action, specifically the webapp-url output so I can pass it to another step in the same job. 

I see that in the action.yaml of there is an outputs defined called: webapp-url but if I try to reference it I get a null value. 

What can be the issue? or what is the correct syntax to access this output?

Thanks in advance,
O.Z

```
    - name: Deploy to WebApp Integ
      uses: azure/webapps-deploy@v2
      id: deploy_webapp
      with:
        app-name: 'poc-asev3-webApp-streamsBack'
        slot-name: 'integ'
        publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
        package: poc-webapp-streams\Streams.WebApi.${{ github.run_number }}.zip

   - run: echo url: ${{ steps.deploy_webapp.output.webapp-url }}/api/v1/status

```

**Comment by orenzi-tr** [comment]
Well at the end i solved this issue in the following way:

```
- name: Deploy to WebApp slot Integ
  uses: azure/webapps-deploy@v2
  id: deploy
  with:
    app-name: 'poc-asev3-webApp-streamsBack'
    slot-name: 'integ'
    publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
    package: ${{ steps.package_path.outputs.PACKAGE }}

- name: Check WebApp Health
  uses: jtalk/url-health-check-action@v1.5
  with:
    url: ${{ steps.deploy.outputs.webapp-url }}/${{ github.event.inputs.healthcheck }}
```

My mistake that I used output instead of outputs, capital S. in the URL: section of the last action.
The vs Code extension didn't pick up this small error
