### DISCUSSION TITLE
New Version Release

### DISCUSSION THREAD

**Discussion by sgollapudi77** [Azure/webapps-deploy#368] [Show and tell]
# Release v3 🎉
Released a new version of the Gh action `webapps-deploy` - **v3**. With the new deploy feature, there are more options you can provide in the action parameters. To know more about the release visit [here](https://github.com/Azure/webapps-deploy/releases/tag/v3.0.0).

## Features
- New workflow parameter `type` - The type of the artifact being deployed, this sets the default target path and informs the web app how the deployment should be handled. 
    - Allowed values: `JAR, WAR, EAR, ZIP, Static`
    - Ex: `- type=war: Deploy a WAR package. By default, the WAR package is deployed to /home/site/wwwroot/app.war. The target path can be specified with parameter target-path.`
- New workflow parameter `target-path` - The absolute path to deploy the artifact to.
    - Allowed value: `{string}`
    - Ex: `/home/site/wwwroot` 
- New workflow parameter `clean` - Specifies whether to clean (delete) the target deployment before deploying the artifact there.
    - Allowed values: `true/false`
    - Ex: `clean=true`
- New workflow parameter `restart` - By default, the API restarts the app following the deployment operation (restart=true). To deploy multiple artifacts, prevent restarts on all but the final deployment by setting restart=false.
    - Allowed values: `true/false`
    - Ex: `restart=true`

### Example
```
- name: Deploy to Azure Web App
  id: deploy-to-webapp
  uses: azure/webapps-deploy@v3
  with:
    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: '*.war'
    type: (jar, war, zip, static)
    clean: (true, false)
    target-path: (i.e. /home/site/wwwroot/test, /home/site/wwwroot/test.war)
    restart: (true, false)
```
