### DISCUSSION TITLE
Why does webapps-deploy action fail when called from another workflow

### DISCUSSION THREAD

**Discussion by caboodal** [Azure/webapps-deploy#426] [Q&A]
I have a workflow that successfully deploys my webapp to an Azure web app service when run in isolation however when I call that same workflow from another workflow it fails with: -

Error: Deployment Failed, Error: No credentials found. Add an Azure login action before this action. For more details refer https://github.com/azure/login

I using secrets to supply the publish profile and as said this is works perfectly when I manually run the workflow on its own, here is my triggering workflow: -

````
name: Build, test and deploy apps

on:
    push:
      branches: [ "production" ]
    workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test-deploy-auth:
    uses: ./.github/workflows/build-test-deploy-auth.yml
  build-test-deploy-forms:
    uses: ./.github/workflows/build-test-deploy-forms.yml  
````

**Comment by caboodal** [comment]
OK sorted, being new to Github actions I needed to inherit the secrets as shown below: -

````
name: Build, test and deploy apps

on:
    push:
      branches: [ "production" ]
    workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test-deploy-auth:
    uses: ./.github/workflows/build-test-deploy-auth.yml
    secrets: inherit
  build-test-deploy-forms:
    uses: ./.github/workflows/build-test-deploy-forms.yml   
    secrets: inherit
````
