### ISSUE TITLE
Errors when passing the "configuration-file" setting

### ISSUE THREAD

**Issue by andymccurdy** [Azure/webapps-deploy#102]
I'm trying to deploy a multi-container app from a Github Action. Whenever I pass the "configuration-file" setting to the action, I get the error message: "Deployment Failed with Error: Error: Multi container support is not available for windows containerized web app.".

Here is the YAML I'm using:

```
    - uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ secrets.APP_NAME }}'    # this the same name as the AppService app name.
        configuration-file: 'deploy/docker-compose.yml'     # this is the relative path to my docker-compose file.
        publish-profile: '${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}'    # the publish profile string
        images: '${{ secrets.REGISTRY_NAME }}/${{ secrets.APP_CONTAINER_NAME }}'     # the image the action built in the previous step.
```

This is a Linux app. I can use the same docker-compose file via the azure-cli or the Portal website to configure the app as a multi-container app successfully. This issue appears to be isolated to the Github Action.

I can deploy a single-container app via this action successfully. I'm only getting errors when trying to deploy a multi-container configuration.
