### ISSUE TITLE
Deploy a simple static site

### ISSUE THREAD

**Issue by KirillOsenkov** [Azure/webapps-deploy#114]
I have a GitHub repo with just index.html, scripts.js and styles.css at the root of the repo.

What Yaml do I need to write to deploy these files from the root of the repo as is to an Azure App Service?

Thanks.

**Comment by AmrutaKawade** [comment]
```
- name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: <app-name>
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: <provide path of your folder>
```
