### ISSUE TITLE
Add docs for efficiently deploying Node.js Express apps

### ISSUE THREAD

**Issue by dennisameling** [Azure/webapps-deploy#119]
I have a Node.js Express app (NestJS) which needs the whole `node_modules` folder to be present when running it. When using this GitHub Action is correctly builds the ZIP, but the simply fails after 20-30 mins (can't remember how long exactly it took). There are ~60000 files in the folder (`node_modules` is always huge), so I guess there's just too many files and folders for this to work well.

```
1:58:39 PM REDACTED-app-backend-dev: Processed 23346 files...
1:58:59 PM REDACTED-app-backend-dev: Processed 24335 files...
1:59:19 PM REDACTED-app-backend-dev: Processed 25339 files...
1:59:39 PM REDACTED-app-backend-dev: Processed 26327 files...
1:59:59 PM REDACTED-app-backend-dev: Processed 27136 files...
2:00:19 PM REDACTED-app-backend-dev: Processed 27718 files...
2:00:40 PM REDACTED-app-backend-dev: Processed 28363 files...
2:01:00 PM REDACTED-app-backend-dev: Processed 29270 files...
2:01:20 PM REDACTED-app-backend-dev: Processed 30209 files...
2:01:40 PM REDACTED-app-backend-dev: Processed 30977 files...
2:02:00 PM REDACTED-app-backend-dev: Processed 31585 files...
2:02:20 PM REDACTED-app-backend-dev: Processed 32213 files...
2:02:41 PM REDACTED-app-backend-dev: Processed 32797 files...
2:03:01 PM REDACTED-app-backend-dev: Processed 33157 files...
2:03:21 PM REDACTED-app-backend-dev: Processed 33609 files...
2:03:41 PM REDACTED-app-backend-dev: Processed 34249 files...
2:04:01 PM REDACTED-app-backend-dev: Processed 34861 files...
2:04:21 PM REDACTED-app-backend-dev: Processed 35218 files...
2:04:41 PM REDACTED-app-backend-dev: Processed 35655 files...
2:05:01 PM REDACTED-app-backend-dev: Processed 36304 files...
2:05:21 PM REDACTED-app-backend-dev: Processed 36867 files...
2:05:41 PM REDACTED-app-backend-dev: Processed 37410 files...
2:06:01 PM REDACTED-app-backend-dev: Processed 38014 files...
2:06:21 PM REDACTED-app-backend-dev: Processed 38862 files...
2:06:41 PM REDACTED-app-backend-dev: Processed 39533 files...
2:07:01 PM REDACTED-app-backend-dev: Processed 40256 files...
2:07:02 PM REDACTED-app-backend-dev: An unknown error has occurred. Check the diagnostic log for details.
2:07:04 PM REDACTED-app-backend-dev: Deployment failed.
```

In this case it's much more efficient to simply build the package on the Azure side, rather than using GitHub Actions for that. According to the docs at https://docs.microsoft.com/nl-nl/azure/developer/javascript/tutorial/deploy-nodejs-azure-app-service-with-visual-studio-code, you can simply set `SCM_DO_BUILD_DURING_DEPLOYMENT=1` and `WEBSITE_NODE_DEFAULT_VERSION` in the app settings. Then it will build on the Azure side.

Could you please update the docs to add some info on the `SCM_DO_BUILD_DURING_DEPLOYMENT=1` option? With this setting, my workflow is also greatly simplified:

```YAML
# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Deploy dev backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: REDACTED
        slot-name: Production
        publish-profile: REDACTED
        package: backend
```
