### ISSUE TITLE
Does not seem to support Docker Compose (preview) in app service for containers

### ISSUE THREAD

**Issue by timothyblue** [Azure/webapps-deploy#129]
I have a Web App for Containers service running with this docker-compose

```
version: '3'
services:
  lclient:
    image: timothyblue/client:1.0
    ports:
      - 80:80
    depends_on:
      - server
  server:
    image: timothyblue/server:1.0
    expose:
      - 80
```

I'm trying to update the app service config using this command:
```
- name: Update Azure config
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'myApp'
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    configuration-file: compose.yml
```
However when the pipeline runs I receive this error:
`Error: Deployment Failed with Error: Error: This is not a container web app. Please remove inputs like images and configuration-file which are only relevant for container deployment.`

After looking at the source code I realized that this option is not available using a publish profile and must be used in conjunction with a Azure Service Principal (SPN) and the `azure/login@v1` action`

The functioning script is below:
```
- name: 'Login via Azure CLI'
  uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}

- name: Update Azure config
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'myApp'
    configuration-file: compose.yml
```
