### ISSUE TITLE
Docker image deployment not triggering image pull

### ISSUE THREAD

**Issue by dennisameling** [Azure/webapps-deploy#132]
We use a Docker deployment for our Web App, using the example that was provided here: https://github.com/Azure/actions-workflow-samples/blob/master/AppService/docker-webapp-container-on-azure.yml

The only difference is that we don't do

```YAML
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/nodejsapp:${{ github.sha }}
```
but instead
```YAML
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/nodejsapp:latest <-- we use latest instead of the SHA
```

... because we can't afford to have a new image SHA for every deployment we do and have that pushed to ACR. We only have the `dev` and `latest` tags for now, for our development and production environments, respectively. That's enough for this small app we're building.

Even though the GitHub Action mentions that the deployment has finished:

```
Deploying image ***.azurecr.io/REDACTED:dev to App Service REDACTED-backend-dev
Successfully deployed image to App Service.
Successfully updated deployment History at https://REDACTED.scm.azurewebsites.net/api/deployments/REDACTED
App Service Application URL: http://REDACTED-backend-dev.azurewebsites.net
```

... the App Service doesn't download the latest image. I have to go into the Azure Portal and click "Restart" - then the updated image will be downloaded.

It looks like a similar issue was fixed in Azure Pipelines a while ago: https://github.com/microsoft/azure-pipelines-tasks/issues/9530

**Comment by jorenbroekema** [comment]
Hm yeah I seem to be facing the same problem.. The linked azure pipelines issue was supposedly fixed, but this issue definitely still persists

**Comment by jorenbroekema** [comment]
Am I supposed to make it un-idle before it gets auto-closed? I never know for sure with these bots.

**Comment by indoben** [comment]
I'm having this issue as well. It seems so arbitrary as to when it updates when the image changes and when it straight ignores the change.

**Comment by jorenbroekema** [comment]
Bumping... still having this problem

**Comment by JasonFreeberg** [comment]
@jorenbroekema -- Do you mind sharing your site name? I can take a look and see if there's anything on our end to figure out what's going on

**Comment by jorenbroekema** [comment]
I'm afraid the Azure App has been deleted, my trial expired 😅 

I still have the GitHub repository though, https://github.com/jorenbroekema/azure-node-app/blob/main/.github/workflows/deploy.yml#L45

Here you can see the deploy workflow, and instead of having `${{ github.sha }}` I was using `latest` on the last line of the yml.
I was not using Service Principal, but Publish profile in order to deploy, the action I was using is `azure/webapps-deploy@v2`.

My issue is pretty much identical to @dennisameling  so.. I'm hoping it would be easy to reproduce by taking a repo with the same workflow, any docker image you own, deploy it with the same github action using "latest" tag, change something and republish the image under "latest", and you should see that the web app gets deployed, but not with your actual latest change. Restarting the deployment does get the latest image.

**Comment by JasonFreeberg** [comment]
Ah I see, yeah the `latest` tag is the crux of the problem. Since the name of the image isn't actually changing, the API doesn't recognize it as a deployment. Restarting the web app always triggers a pull, so that's why the manual restarts are solving the issue. 

This problem is at the API, so the Action could force-trigger a restart if the tag is `latest`, but other clients (VS Code, Pipelines) will still run into this

**Comment by jorenbroekema** [comment]
Hmm so at the API level, I assume some check like `if (old.tag === new.tag) { return; }` is done, would it make sense to remove this check or would that be throwing out the baby with the bathwater?

One solution could be to add a check for the tag "latest" but if you've got other distribution tags where it still needs to trigger, the problem will persist for those non-latest tags. 

Another solution which I think makes more sense in checking that the image has changed since last deploy, is by checking the image digest (sha256 string), if that one changed since last time you know for sure whether you should trigger a deploy, regardless of whether the tag changed or not.

**Comment by kumaraksh1** [comment]
Hi,
We have investigated this issue and we will be working on it soon.

**Comment by sgollapudi77** [comment]
Not able to reproduce this.

**Comment by EstebanZ** [comment]
Hi, I'm experiencing the same problem, with the same configuration described by dennisameling:

```yaml
name: Deploy Web App
env:
    TAG: ${{ vars.PROJECT_TAG }}
on:
  workflow_dispatch:
jobs:
  deploy:
    # this permission contents is set to none to avoid exposing the secrets to the action
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}
```

Where the environment variable ```PROJECT_TAG = latest```.
I share information about the web app:

Hosting
- Plan Type: App Service Plan
- SO: Linux
- Instances: 1
- SKU: P1v2

Deployment Settings
- source: Container Registry

GitHub Action output:
```log
Run azure/webapps-deploy@v2
  with:
    app-name: *******
    images: ***.azurecr.io/webapp/webapp:latest
    slot-name: production
    package: .
  env:
    AZURE_WEBAPP_NAME: *******
    LOGIN_SERVER: ***.azurecr.io
    REGISTRY_USERNAME: ***
    REGISTRY: ***.azurecr.io
    REPOSITORY: webapp
    IMAGE: webapp
    TAG: latest
    PROJECT_GLOBAL_DEVICE_ENDPOINT: ***
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Updating App Service Configuration settings. Data: ***"linuxFxVersion":"DOCKER|***.azurecr.io/*****:latest"***
Updated App Service Configuration settings.
Restarting app service: *******
Deployment passed
Restarted app service: *******
Successfully updated deployment History at https://*******.scm.azurewebsites.net/api/deployments/******************
App Service Application URL: https://*******.azurewebsites.net
```
