### ISSUE TITLE
ACR url should deploy with Registry source as Azure Container Registry

### ISSUE THREAD

**Issue by rawilder** [Azure/webapps-deploy#136]
When using the following action config, it will deploy to the webapp instance configured with the Registry source as "Private Registry" which makes the deployment fail requiring a username and password. With managed identity, it should be fine setting it to Azure Container Registry so the existing permissions allow a smooth experience.

Workaround: Change the Registry source to Azure Container Registry after the first deploy with the matching container, then future actions seem to apply that. 

```
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: ${{ env.APP_NAME }}
          # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
          images: ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}
          # Enter the start up command. For ex. dotnet run or dotnet run
          startup-command: /home/app/start.sh
```
