### ISSUE TITLE
Multi-Container Deployment stopped working

### ISSUE THREAD

**Issue by wapacro** [Azure/webapps-deploy#162]
For two different and unrelated Azure multi-container web apps (using the same shared app service plan), deploying with the Azure/webapps-deploy@v2 action via GitHub Actions suddenly stopped working.

The webapps-deploy action always fails with:
```
Error: Deployment Failed with Error: Error: This is not a container web app. Please remove inputs like images and configuration-file which are only relevant for container deployment.
```

The last deployments from May 24, 2021 and before worked smoothly with the same pipeline. Also, nothing has been changed on the web app in the meantime.

There is no doubt that the apps are container apps. This is shown by the following output of the AZ CLI:
```shell
$ az webapp show -n app-cope-uac-dev -g rg-xxx-northeurope
[ ... ]
"kind": "app,linux,container",
"linuxFxVersion": "COMPOSE|dmVy ... 2VyCg==",
[ ... ]
```

To be on the safe side, I also deleted one of the two apps again and rebuilt it from scratch as a Docker Compose app via Azure Portal - starting the pipeline afterwards ended with the same result.

<details>
  <summary>GitHub Actions Workflow</summary>

  ```yaml
  configure-azure:
    name: Configure Azure Environment
    runs-on: ubuntu-20.04
    needs: [ "test" ]
  
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SERVICE_USER] }}
      - name: Configure Authentication for GitHub Package Registry
        uses: azure/cli@v1
        env:
          TOKEN: ${{ secrets[env.GH_SERVICE_USER] }}
        with:
          inlineScript: |
            az webapp config container set --name ${APPSERVICE_APP_NAME} --resource-group ${APPSERVICE_RESOURCE_GROUP} \
              --docker-registry-server-user "XXX" --docker-registry-server-password "${TOKEN}" \
              --docker-registry-server-url "https://${IMG_REGISTRY}"
  
  deploy-container:
    name: Deploy App Container
    runs-on: ubuntu-20.04
    needs: [ "build-container", "configure-azure" ]
  
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SERVICE_USER] }}
      - name: Prepare Deployment
        uses: microsoft/variable-substitution@v1
        with:
          files: './.azure/deploy/deployment.yml'
        env:
          services.web.image: "${{ env.IMG_REGISTRY }}/${{ github.REPOSITORY }}:${{ env.IMG_TAG }}"
          services.worker.image: "${{ env.IMG_REGISTRY }}/${{ github.REPOSITORY }}:${{ env.IMG_TAG }}"
      - name: Deploy Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APPSERVICE_APP_NAME }}
          configuration-file: ./.azure/deploy/deployment.yml
  ```
</details>

<details>
  <summary>/.azure/deploy/deployment.yml</summary>

  ```yaml
  version: '3.8'
  
  services:
    web:
      image: "<INSERTED BY CI/CD>"
      restart: always
      ports:
        - "8080:8080"
    worker:
      image: "<INSERTED BY CI/CD>"
      restart: always
      entrypoint: /cnb/process/worker

  ```
</details>

![image](https://user-images.githubusercontent.com/11590853/120934380-7ad98280-c6fe-11eb-9f2a-e6803759a833.png)

Feedback highly appreciated 😃
