### ISSUE TITLE
App Service settings not exposed as environment variables inside Docker container

### ISSUE THREAD

**Issue by NLeRoy917** [Azure/webapps-deploy#187]
Hello,

I've been having this issue for a while where App Settings that I set within my App Service on the Azure Portal **are not** injected within the docker container itself on build and push or deploy. I followed [this](https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#configure-environment-variables) guide, but it did not work.

More specifically, we've got a React application that requires some environment secrets... and typically these are exposed as environment variables of the form `REACT_APP_*`. I have a few set in the app service configurations, but when you `console.log` out the `process.env` object (where these variables are stored)... they are not present:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/41063083/124326166-0276ad80-db54-11eb-9f50-8b1fb03b1054.png">

Even though they can be seen at the `/Env` url for our application:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/41063083/124326238-1cb08b80-db54-11eb-87ca-b6f5062220c7.png">

This is what the workflow configuration looks like for our GitHub action during the docker build and push stage:

```yaml
    - run: |
        docker build "$GITHUB_WORKSPACE/client" -f  "client/Dockerfile" -t sdmmappingacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a28fca83064349029b23350b348e3409 }}/sdmmappingui-img:${{ github.sha }}
        docker push sdmmappingacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a28fca83064349029b23350b348e3409 }}/sdmmappingui-img:${{ github.sha }}
```

I attempted to generate a `.env` file during the workflow using a custom shell script and the Dockerfile would copy it over manually, but I believe that the contents of `printenv` during this are just the env variables of the actual runner used to build the docker containers prior to push.

Am I missing something? Or misunderstanding something? I'd love to be able to use environment variables in our projects... Any help is appreciated!

**Comment by NLeRoy917** [comment]
Solved. I'm using GitHub actions and was able to employ the `azure/CLI@v1` [action](https://github.com/marketplace/actions/azure-cli-action). I'm just manually extracting App Settings from the Azure CLI and then piping that output to a custom python script and piping **that** to a `.env` file that gets pulled into the Docker container on build and thus, exposes all variables in that file with a `REACT_APP_` prefix.

**Workflow file:**
```yaml
    - name: Extract App Settings
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/scripts/az_to_env.py
          echo "-----> Copying settings to .env file."
          az webapp config appsettings list --name <app-name> --resource-group <resource-group> --subscription <subscription> | $GITHUB_WORKSPACE/scripts/az_to_env.py > $GITHUB_WORKSPACE/client/.env
```

**Python script:**
```python
#!/usr/bin/env python3
import sys
import json

# read json from standard in
json_data = sys.stdin.read()
keys_list = json.loads(json_data)

for key in keys_list:
    print(f"{key['name']}={key['value']}")
```

A limitation is that you must rebuild your application to reflect app setting changes, but this was simple and intuitive to me and more secure.
