### ISSUE TITLE
Getting 404 when deploying

### ISSUE THREAD

**Issue by ardalis** [Azure/webapps-deploy#192]
This if for a public repo you can see here:
https://github.com/DevBetterCom/DevBetterWeb

Running the CI/CD workflow (github action), everything works until the deploy step, when I get back a 404 result. Here's the failing log:

![image](https://user-images.githubusercontent.com/782127/132738096-19864b33-58bb-48eb-a5df-ca300b6db12d.png)

I've been searching and I can't find any information on why one might get a 404 here. I don't see anything in the Azure Portal for this app (though I admit I'm not sure where to look). I just tried switching the deploy step to use Windows instead of Ubuntu - not sure if that will make a difference. Any ideas?

**Comment by ardalis** [comment]
Ok, so, it worked once I switched to using windows.

![image](https://user-images.githubusercontent.com/782127/132738687-aa52792d-e59e-4fa1-a516-7b16496cc210.png)

Here's the YAML (https://github.com/DevBetterCom/DevBetterWeb/blob/main/.github/workflows/ci-cd.yml):

```
cd:
    if: needs.ci.outputs.is_push_to_default_branch == 'true'
    name: Continuous Deployment
    needs: ci
    runs-on: windows-latest
    steps:
      - name: Download publish artifacts
        id: dl_publish_artifacts
        uses: actions/download-artifact@v2
        with:
          name: Publish artifacts
          path: WebApp/

      - name: Azure webapp deploy with Publish Profile
        id: azure_webapp_deploy_with_publish_profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WebApp'
```

Only thing I changed is `runs-on` to `windows-latest` from ubuntu. Is this a known issue? Some kind of case sensitivity?
