### ISSUE TITLE
Generating deployment script, fails due to invalid path

### ISSUE THREAD

**Issue by wmmihaa** [Azure/webapps-deploy#196]
## Background
I raised this issue before (#42), but as it took too long to resolve, I moved on to other solutions. As I'm now working on a new project, I though I give it another chance, sadly to discover the issue has yet not been resolved.

## Solution set up:
I have a solution with ASP.Net web app together with a few other projects. All projects are .Net5 except one which is .Net3.1 (Azure Functions). All project folders resides under the same solution folder:
- Solution folder
   - Project folder
   - Project folder
   - Project folder

## Problem 
I'm trying to deploy the web application to an Azure Web App Slot (dev). So far I have only tried it using a Windows host.

I've tried generate my deployment.yml file both from Azure portal and from with in Visual Studio 2019, both with the same issue related to the `azure/webapps-deploy@v2` step.

```bash
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id '09ee5b10f6'.
Generating deployment script.
Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted\GreenEdge.Web"'
```

**The problem is the `sitePath`. The `extracted` directory holds all the binaries (build output) and there is no GreenEdge.Web directory (btw "GreenEdge.Web" is the name of  the project and the folder it's in).**. (the project output directory is "D:\a\GreenEdge\GreenEdge\GreenEdge.Web\publish")

## Logs and build scripts
I've attached the logs, and the yml is found below:
[build.log](https://github.com/Azure/webapps-deploy/files/7181117/build.log)

```yaml
name: Build and deploy .NET Core app to Windows WebApp greenedge-web
on:
  push:
    branches:
    - dev
env:
  AZURE_WEBAPP_NAME: greenedge-web
  AZURE_WEBAPP_SLOT_NAME: dev
  AZURE_WEBAPP_PACKAGE_PATH: GreenEdge.Web/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.greenedge_web_dev_75dd }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: GreenEdge.Web
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: List package path
      run: ls "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

```
