### ISSUE TITLE
Deployment fails for docker compose / multi-container setup

### ISSUE THREAD

**Issue by lehtiton** [Azure/webapps-deploy#203]
I cannot get the multi-container deployment working with azure/webapps-deploy action. I have tried so many different combinations of settings. I do get the multi-container stuff working when configuring manually from azure portal web app deployment center.

This is how I thought it to work from Github pipeline yml:

    - name: Update Azure Web App container image
      uses: azure/webapps-deploy@v2.2.3
      with:
        app-name: 'test-app'
        configuration-file: 'docker-compose.yml'

But it always gives the following error:
"Error: Deployment Failed with Error: Error: For single-container, just specify a valid image name. For multi-container specifying a Docker-Compose file is mandatory and specifying image names is optional. Provide image names if the tags in Docker-Compose file need to be substituted."

I have also tried to list down docker images via images attribute. While doing that the github action did pass successfully, but it configured Azure web app as Single Container deployment => web app failed.

What am I doing wrong / any suggestions how to proceed to get the pipeline working?

**Comment by BALAGA-GAYATRI** [comment]
@lehtiton Are you using login action before calling this? If not you should use. You can directly use `azure/webapps-deploy@v2` and also please check if your `docker-compose` file path is valid or not. You may refer to [sample workflows](https://github.com/Azure/webapps-deploy#create-azure-web-app-and-deploy-using-github-actions).

**Comment by rahulaga-msft** [comment]
@lehtiton were you able to try with steps suggested above _Are you using login action before calling this? If not you should use. You can directly use azure/webapps-deploy@v2 and also please check if your docker-compose file path is valid or not. You may refer to sample workflows._

**Comment by shpraka** [comment]
@lehtiton were you able to get it working from the steps provided earlier?

**Comment by JorritBootsma** [comment]
I am running into the same issue.

deploy.yml:
```
name: Deploy to Azure Web Service

# Controls when the workflow will run
on:
  # Triggers the workflow on newly pushed tags of specific format
  push:
#     branches:
#       - "main"
    tags:
      - "v*.*.*"
      - "!v*.*.*-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # This step logs into Azure using a Service Principal Name (SPN) as an alternative to the "Publish Profile"
      - name: Azure Login with secrets.AZURE_CREDENTIALS
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2  # This action triggers an App restart in Azure App Service
        with:
          app-name: 'multi-container-app'
          configuration-file: 'docker-compose.yml'

      # Echo the results
      - name: URL
        run: |
          echo ${{ steps.deploy-to-webapp.outputs }}
          echo ${{ steps.deploy-to-webapp.outputs.webapp-url }}
```

This fails with: 
--
Deployment Failed with Error: Error: For single-container, just specify a valid image name. For multi-container specifying a Docker-Compose file is mandatory and specifying image names is optional. Provide image names if the tags in Docker-Compose file need to be substituted.

My project folder structure:
![Screenshot 2022-10-27 at 14 11 52](https://user-images.githubusercontent.com/17005018/198280966-d1eb781b-238f-4c65-a518-cbf0a81e53f7.png)

The Github repo I work in, for reference: 
https://github.com/JorritBootsma/multi-container-app
