### ISSUE TITLE
Deployment Python Azure Webapp results in error 404  Not Found [IP: ..]

### ISSUE THREAD

**Issue by erfannariman** [Azure/webapps-deploy#205]
This was working fine until couple days ago, each deployment results in the following error:

```
Run sudo apt install python3.8-venv
  sudo apt install python3.8-venv
  python -m venv --copies antenv
  source antenv/bin/activate
  pip install setuptools
  pip install -r requirements.txt
  shell: /bin/bash -e ***0***
  env:
    AZURE_WEBAPP_NAME: sampling
    WORKING_DIRECTORY: .
    PYTHON_VERSION: 3.8
    STARTUP_COMMAND: 
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libpython3.8-minimal libpython3.8-stdlib python3.8 python3.8-minimal
Suggested packages:
  python3.8-doc
The following NEW packages will be installed:
  libpython3.8-minimal libpython3.8-stdlib python3.8 python3.8-minimal
  python3.8-venv
0 upgraded, 5 newly installed, 0 to remove and 13 not upgraded.
Need to get 4556 kB of archives.
After this operation, 18.5 MB of additional disk space will be used.
Ign:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.8-minimal amd64 3.8.0-3~18.04.1
Ign:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.8-minimal amd64 3.8.0-3~18.04.1
Ign:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.8-stdlib amd64 3.8.0-3~18.04.1
Ign:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.8 amd64 3.8.0-3~18.04.1
Ign:5 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.8-venv amd64 3.8.0-3~18.04.1
Err:1 http://security.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.8-minimal amd64 3.8.0-3~18.04.1
  404  Not Found [IP: 52.154.174.208 80]
Err:2 http://security.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.8-minimal amd64 3.8.0-3~18.04.1
  404  Not Found [IP: 52.154.174.208 80]
Err:3 http://security.ubuntu.com/ubuntu bionic-updates/universe amd64 libpython3.8-stdlib amd64 3.8.0-3~18.04.1
  404  Not Found [IP: 52.154.174.208 80]
Err:4 http://security.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.8 amd64 3.8.0-3~18.04.1
  404  Not Found [IP: 52.154.174.208 80]
Err:5 http://security.ubuntu.com/ubuntu bionic-updates/universe amd64 python3.8-venv amd64 3.8.0-3~18.04.1
  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.8/libpython3.8-minimal_3.8.0-3~18.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.8/python3.8-minimal_3.8.0-3~18.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.8/libpython3.8-stdlib_3.8.0-3~18.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.8/python3.8_3.8.0-3~18.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.8/python3.8-venv_3.8.0-3~18.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

And this is our YAML:

```yaml
name: Deploy App to Azure Web App.
on:
  push:
    branches:
      - development
env:
  AZURE_WEBAPP_NAME: name # set this to your application's name
  WORKING_DIRECTORY: '.'         # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: '3.8'
  STARTUP_COMMAND: ''           # set this to the startup command required to start the gunicorn server. default it is empty

jobs:
 build-and-deploy:
  runs-on: ubuntu-18.04
  steps:
  - uses: actions/checkout@master

  - name: Setup Python
    uses: actions/setup-python@v1
    with:
     python-version: ${{ env.PYTHON_VERSION }}

  - name: python install
    working-directory: ${{ env.WORKING_DIRECTORY }}
    run: |
     sudo apt install python${{ env.PYTHON_VERSION }}-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt

  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
  - uses: azure/appservice-settings@v1
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     mask-inputs: false
     general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
  # deploy web app
  - uses: azure/webapps-deploy@v2
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     slot-name: 'dev'
     package: ${{ env.WORKING_DIRECTORY }}
     startup-command: ${{ env.STARTUP_COMMAND }}
  # Azure logout
  - name: logout
    run: |
     az logout
```
