### ISSUE TITLE
Deployment Failed with Error: LinuxFxVersion or WindowsFxVersion should not be null or both set, and should be of the format 'DOCKER|<image_tag>'. eg: DOCKER|appsvc/node:12-lts_20200101.1

### ISSUE THREAD

**Issue by henrikcomes** [Azure/webapps-deploy#212]
I have an Azure App Service of kind "app,linux,container".
Building and Pushing my Docker Image is working completely fine and my build shows up in my registry.
But the deployment step is just not working.

This is the error I get when running the action:

> Run azure/webapps-deploy@v2
>   with:
>     app-name: myapp
>     publish-profile: ***
>     images: ***.azurecr.io/myapp:${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}
>     slot-name: production
>     package: .
> Deploying image ***.azurecr.io/myapp:${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER} to App Service myapp
> Error: Failed to deploy image to Web app Container.
> Error: Deployment Failed with Error: LinuxFxVersion or WindowsFxVersion should not be null or both set, and should be of the format 'DOCKER|<image_tag>'. eg: DOCKER|appsvc/node:12-lts_20200101.1
> Successfully updated deployment History at https://myapp.scm.azurewebsites.net/api/deployments/ced9d22d59d7f0677d5e679d7e18e444beec59701642630164212
> App Service Application URL: https://myapp.azurewebsites.net

In my App Service Template I only have LinuxFxVersion twice and it is the same value.
`"linuxFxVersion": "DOCKER|myregistry.azurecr.io/app:1720470697.14"`

I tried adding `DOCKER|` infront of my image name, as suggested in the error, but that also did not work.

Currently I am running a B1 App Service that does not have Staging Slots.
Do I need them because the Logs say `slot-name: production`?

Here is my workflow file:

```
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    
    - name: Docker Tag
      run: docker tag myregistry.azurecr.io/myapp:latest myregistry.azurecr.io/app:${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}
      
    - name: Docker Login
      run: docker login myregistry.azurecr.io -u ${{ secrets.CR_USERNAME }} -p ${{ secrets.CR_TOKEN }}
      
    - name: Docker Push
      run: docker push myregistry.azurecr.io/myapp:${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        images: myregistry.azurecr.io/myapp:${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}
```
