### ISSUE TITLE
Error: Resource {app-service-name} doesn't exist (but it definitely does)

### ISSUE THREAD

**Issue by donniehale-awh** [Azure/webapps-deploy#227]
The output from the `azure/webapps-deploy@v2` step is:

```sh
Error: Deployment Failed with Error: Error: Resource my-api-app doesn't exist.
```

(Resource names changed, but I've done string comparisons.)

I'm using the same workflow yaml in this product/repository as I'm using in another one where it's working fine - pretty straightforward:

```yaml
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    # Hopefully temporary
    # Got an error in the next step (webapps-deploy) that the app service doesn't exist...
    # But it does, and this command will hopefully verify that it's visible via the prevous azure/login
    # and that it can be seen via its name.
    - name: Verify app service
      run: |
        az webapp config appsettings list --name my-api-app --resource-group my-api-dev-rg --subscription {subscription-id}

    - name: Deploy to Development environment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.update_env.outputs.API_APP_SERVICE_NAME }}
        package: ${{ github.workspace }}/${{ env.API_PUBLISH_PATH }}
```

I know that the login works and that the app service exists because the `az` command in the `Verify app service` step succeeds and gives this output:

```json
[
  ***
    "name": "ASPNETCORE_ENVIRONMENT",
    "slotSetting": false,
    "value": "Development"
  ***,
  ***
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "slotSetting": false,
    "value": "value-redacted"
  ***,
  ***
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "slotSetting": false,
    "value": "InstrumentationKey=value-redacted"
  ***,
  ***
    "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
    "slotSetting": false,
    "value": "1.0.0"
  ***,
  ***
    "name": "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
    "slotSetting": false,
    "value": "1.0.0"
  ***
]
```

I honestly don't know what more I can do to troubleshoot this or to achieve a workaround.

Any input from anyone? Thanks.
