### ISSUE TITLE
Step doesn't respect ${{ env.GITHUB_RUN_NUMBER }}

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/webapps-deploy#235]
I'm using this action to deploy my built image and `${{ env.GITHUB_RUN_NUMBER }}` to set the image tag, but it doesn't doesn't appear to work:

Here's the code ([link](https://github.com/lastcoolnameleft/duckiehunt/blob/20f43f704ab53ebf29d89d7171ba0de632d40ae9/.github/workflows/docker-image-build-push-deploy.yml#L40)):

```
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/gh/duckiehunt:${{ env.GITHUB_RUN_NUMBER }}
```

Here's the action output ([link](https://github.com/lastcoolnameleft/duckiehunt/runs/6510606333?check_suite_focus=true))

```
Run azure/webapps-deploy@v2
  with:
    app-name: ***
    images: ***/gh/***:
    slot-name: production
    package: .
```

As you can see the image does not have the tag in the full image name.  When I go to the Azure Portal, it has the correct image, but then the tag is blank (and then the WebApp is broken)

Expected result:  I expect it to deploy with the GITHUB_RUN_NUMBER tag (in this case, 5).

NOTE:  If I use `${{ github.sha }}` then that works; however, that's not the setting I'm trying to use.
