### ISSUE TITLE
How to deploy single project from ASP.NET 4.8 solution?

### ISSUE THREAD

**Issue by jsodeman** [Azure/webapps-deploy#236]
I have a solution that holds multiple web apps in sub-folders. Using the setting below, the contents of the entire solution end up being copied onto the Azure Web App. Is there a way to use this action to deploy a single project?

```
    - name: Build step
      run: msbuild SiteFolder\Site.csproj -p:Configuration=Debug

    - name: Azure deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_SITE_NAME }}
        publish-profile: ${{ secrets.AZURE_PROFILE }}
```

**Comment by jsodeman** [comment]
I found the answer, I needed to use a folder publish profile in the build step and then point the deploy to that folder.

```
    - name: Build step
      run: msbuild SiteFolder\Site.csproj -p:DeployOnBuild=True -p:PublishProfile="FolderProfile" -p:PublishProfileRootFolder=D:\a\MyApp\MyApp\SiteFolderI\Properties\PublishProfiles -p:Configuration=Debug

    - name: Azure deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_SITE_NAME }}
        publish-profile: ${{ secrets.AZURE_PROFILE }}
        package: D:\a\MyApp\MyApp\SiteFolder\bin\app.publish
```

```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <DeleteExistingFiles>false</DeleteExistingFiles>
    <ExcludeApp_Data>false</ExcludeApp_Data>
    <LaunchSiteAfterPublish>true</LaunchSiteAfterPublish>
    <LastUsedBuildConfiguration>Debug</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <PublishProvider>FileSystem</PublishProvider>
    <PublishUrl>bin\app.publish\</PublishUrl>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <SiteUrlToLaunchAfterPublish />
  </PropertyGroup>
</Project>
```
