### ISSUE TITLE
Action never times out if the target web app does not exist

### ISSUE THREAD

**Issue by 8osm** [Azure/webapps-deploy#237]
### Workflow File (sensitive info redacted)
```yaml
name: Build and deploy Python app to Azure Web App - web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Env'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'web-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
```

### Web App environment
- Linux Web App
- Python 3.9
- P1v2 ASP

### Steps to reproduce the issue
1. Create an Azure Web App
2. Export the publish profile and import it as a secret into GitHub
3.  Create a workflow that uses this secret as a publish profile for the action
5. Delete the Web App created in the first step
6. Run the workflow, the workflow will hang trying to publish it but will timeout after 6 hours (GitHub's hard cap on workflows)

### Expected behavior
The action should report a fail when the publish profile is invalid.

### Actual behavior
The deploy job using this action hangs until killed by GitHub or the user.

**Comment by JasonFreeberg** [comment]
@surenderssm -- In the immediate term it would be good to set a more reasonable timeout for this (such as 1 hour). An optional parameter would also be a nice addition:

```yaml
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'web-app'
          slot-name: 'production'
          timeout: '30m'  # or '1h' or '60s', etc. 
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
```
