### ISSUE TITLE
Unable to connect to private GitHub package repository

### ISSUE THREAD

**Issue by lanesawyer** [Azure/webapps-deploy#251]
Hi,

I'm trying to use the `azure/webapps-deploy@v2` GitHub Action to publish my site to Azure, but I'm running into trouble because I'm using a private GitHub package repository. I haven't been able to find any documentation related to this online, so I'm hoping asking here will get me some help.

When it runs, I get the following error:

`npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/[my private package here] - authentication token not provided`

I saw this error while setting up other Actions, and using the `NODE_AUTH_TOKEN` or `GPR_TOKEN` environment variables seemed to have done the trick, but using either doesn't seem to work with `azure/webapps-deploy@v2`

My `yml` looks like this:
```
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vm-backend-staging'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_RANDOM_ID }}
          package: ${{ env.AZURE_WEBAPP_ROOT_PATH }}/${{ env.ZIP_PACKAGE_NAME }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
```

On a slightly related note that could get me past the blocker, I'm confused as to why `azure/webapps-deploy@v2` is even running `npm install` because I have an artifact downloaded in the step before that I thought the Action was using.

My co-workers and I were having trouble getting the GitHub Action working so we sat down with an Azure help representative for a few hours and the artifact upload/download process was what that employee told us made it all work, but since the step is failing to authenticate with the GitHub package repository on an `npm install` I see in the logs, I am now doubting it's using the artifact at all... If we could use the artifact, that already has everything built for deployment and thus the need to connect to the private GitHub registry could be avoided.

Thank you in advance for the advice!
