### ISSUE TITLE
Specify resource group or app service environment.

### ISSUE THREAD

**Issue by ayuina** [Azure/webapps-deploy#256]
Deployment failed when there are multiple app services which have same name. Of course we can't create Non-ASE app service which have duplicate name because all app services have same domaim suffix (azurewebsites.net) . But ASE app service can have duplicate name because ASE has unique domain suffix (asename.appserviceenvironment.net) each other. 

This action seems to search app service instance by the name only, but the name may not be unique in ASE app service. So I think this action should have option to specify the resource group or environment for uniqueness.

workflow file is below, 
```yaml
      - name: Deploy to Azure Web App in ILB ASE v2
        id: deploy-to-app2
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app2'
          package: .
```

but there are multiple app service named "app2".
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1955999/196166966-b14de9c3-54f8-440c-b2fd-a8c69ff76c15.png">

and workflow fail with this error.
```
Run azure/webapps-deploy@v2
  with:
    app-name: app2
    package: .
    slot-name: production
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Error: Deployment Failed with Error: Error: Multiple resource group found for resource nameapp2
```
