### ISSUE TITLE
npm ERR! Error: EACCES: permission denied error during azure/webapps-deploy@v2

### ISSUE THREAD

**Issue by elleklinton** [Azure/webapps-deploy#257]
Hi,

We use this workflow for our Azure deployment, and suddenly, the deployments started failing with this permissions error:
```
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/abbrev
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/abbrev'
npm ERR!  [Error: EACCES: permission denied, access '/opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/abbrev'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/abbrev'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

Before this errors out, a bunch of similar warnings are printed out:
```
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/abbrev
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/ansi-align
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/ansi-regex
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/ansicolors
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/ansistyles
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/aproba
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/are-we-there-yet/node_modules/string_decoder
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/asap
npm WARN checkPermissions Missing write access to /opt/nodejs/14.19.1/lib/node_modules/npm/node_modules/asn1
...
```

This was working perfectly fine a couple weeks back, but suddenly errors out with this error whenever we try to deploy. Happy to share anything I can to get this fixed. It seems like an odd error to be getting during deployment, especially because `npm install` has already been run as a pre-step to this (successfully). 

This is a particularly critical failure for us, as it's preventing us from deploying a bug fix in production.

This is our full github actions workflow yml that is failing:
```
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy

on:
  pull_request:
    branches:
      - production
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run compile
        npm run test --if-present

    - name: Compress files as zip
      run: tar cf archive.tar .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: archive.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: Unzip compressed files
      run: tar xf archive.tar

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'edify-safetymojo-api-sandbox'
        slot-name: 'production'
        publish-profile: ${{ <removed secret> }}
        package: .
```
