### ISSUE TITLE
Deploying static index.html to Azure App Service does not publish anything

### ISSUE THREAD

**Issue by MattLavalleeMA** [Azure/webapps-deploy#298]
Similar to Issue #114, I am trying to deploy a single HTML file (index.html) to an Azure App Service (Windows) with minimal yaml:

```
name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'xxxxappname'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILExxxx }}
```

The Action is triggered successfully, the deployment completes successfully, but nothing is published to my App Service.  The wwwroot is empty, and inspecting the deployment's manifest in Kudu shows no files.

Am I missing a step? There are lots of samples for built/compiled apps, but I couldn't find anything for simple xcopy-type publishing.
