### ISSUE TITLE
deploying WebJob

### ISSUE THREAD

**Issue by srijken** [Azure/webapps-deploy#3]
How can this be used to deploy a WebJob project to an AppService?

**Comment by ehamai** [comment]
@srijken - Web jobs are just regular file content, so there shouldn't be anything special required in order to deploy them.  Building them may be a different story of course, but for this repo which is specific to the deployment action, I don't see why it would be anything different.  Are you running into issues with it?

**Comment by jstevense-vbe** [comment]
Here is a working example for you brother. Just setup the publish profile as a secret and your done.
And of course change the variables.

`name: Deploy WebJob

on:
  workflow_dispatch:

  push:
    branches: [ develop ]

env:
  WEBJOB_NAME: YourWebJobName
  AZURE_APP_NAME: your-azure-app-service-name
  PROJECT_ROOT: path/to/your/Project.Root
  TEST_PROJECT_ROOT: path/to/your/Project.Root.Tests
  DOTNET_VERSION: '3.1.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: dotnet test
      run: |
        dotnet test ${{ env.TEST_PROJECT_ROOT }}

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o './publish/App_Data/Jobs/Triggered/${{ env.WEBJOB_NAME }}' ${{ env.PROJECT_ROOT }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './publish'`

**Comment by joeystdio** [comment]
Here is a working example for you my friend. Just setup the publish profile as a secret and your done.
(and of course change the variables)

`name: Deploy WebJob

on:
  workflow_dispatch:

  push:
    branches: [ develop ]

env:
  WEBJOB_NAME: YourWebJobName
  AZURE_APP_NAME: your-azure-app-service-name
  PROJECT_ROOT: path/to/your/Project.Root
  TEST_PROJECT_ROOT: path/to/your/Project.Root.Tests
  DOTNET_VERSION: '3.1.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: dotnet test
      run: |
        dotnet test ${{ env.TEST_PROJECT_ROOT }}

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o './publish/App_Data/Jobs/Triggered/${{ env.WEBJOB_NAME }}' ${{ env.PROJECT_ROOT }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './publish'`

**Comment by ianrandell-sh** [comment]
@joeystdio - perfect!  I've been trying for hours to get it to work.  The key for me was getting the files deployed to the right place, i.e under app_data/jobs/continuous.

I couldn't find a single piece of documentation that explained how to do the whole thing. Wish I'd hit your post above sooner- would've saved me going round the houses.

Note: the above also works with azure login rather than publish profiles which didnt work for me, ie:

```yaml
      # ---------------------------------------------
      # Login using Service-Principal-type secret
      # See: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=userlevel#configure-the-github-secret
      # ---------------------------------------------
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_WEBJOB_CREDENTIALS_DEV}}

      # Deploy to Azure Web apps
      - name: Deploy to Azure App Service ${{env.AZURE_APPSERVICE_NAME}}
        uses: azure/webapps-deploy@v2
        with: 
          app-name: '${{env.AZURE_APPSERVICE_NAME}}'
          package: '${{env.PUBLISH_OUTPUT_ROOT}}'
      
      - name: logout
        run: |
          az logout
```
