### ISSUE TITLE
Deployment Fails with certain NPM modules

### ISSUE THREAD

**Issue by Fish1** [Azure/webapps-deploy#337]
We are getting errors with the deploy script and running into integrity issues. I am unable to replicate it on my local machine. I've even deleted my node_modules and package-lock.json. I am only able to replicate this on our backend server deployment, the frontend deployment works fine. So the webapps-deploy might seem to be the issue.

[2_Deploy Server.txt](https://github.com/Azure/webapps-deploy/files/11407235/2_Deploy.Server.txt)
[1_Deploy Server.txt](https://github.com/Azure/webapps-deploy/files/11407236/1_Deploy.Server.txt)

[1_Set up job.txt](https://github.com/Azure/webapps-deploy/files/11407262/1_Set.up.job.txt)
[2_Pull Source.txt](https://github.com/Azure/webapps-deploy/files/11407258/2_Pull.Source.txt)
[3_Build And Deploy.txt](https://github.com/Azure/webapps-deploy/files/11407259/3_Build.And.Deploy.txt)
[6_Post Pull Source.txt](https://github.com/Azure/webapps-deploy/files/11407260/6_Post.Pull.Source.txt)
[7_Complete job.txt](https://github.com/Azure/webapps-deploy/files/11407261/7_Complete.job.txt)

/package.json
```json
{
  "name": "shuttle-management",
  "author": "Polar Beverages",
  "version": "1.0.0",
  "description": "This is the shuttle management system for Polar Beverages",
  "scripts": {
    "dev": "npm run dev -w server & npm run dev -w client",
    "build": "npm run build -w server -w client",
    "start": "npm run start -w server & npm run start -w client",
    "test": "npm run test -w client",
    "lint:fix": "npm run lint:fix -w server -w client",
    "lint:check": "npm run lint:check -w server -w client",
    "type:check": "npm run type:check -w server -w client"
  },
  "workspaces": [
    "client",
    "server"
  ]
}
```

server/package.json
```json
{
  "name": "server",
  "private": true,
  "version": "0.0.6",
  "scripts": {
    "dev": "ts-node-dev --respawn --transpile-only ./src/index.ts",
    "build": "tsc",
    "start": "node ./dist/index.js",
    "lint:fix": "eslint --fix .",
    "lint:check": "eslint .",
    "type:check": "tsc --noEmit"
  },
  "dependencies": {
    "@trpc/server": "^10.6.0",
    "body-parser": "^1.20.0",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "dotenv": "^16.0.2",
    "express": "^4.18.1",
    "mariadb": "^3.0.1",
    "passport": "^0.6.0",
    "passport-azure-ad": "^4.3.4",
    "pino": "^8.5.0",
    "pino-http": "^8.2.0",
    "superjson": "^1.11.0",
    "zod": "^3.19.1"
  },
  "devDependencies": {
    "@azure/msal-node": "^1.14.5",
    "@types/compression": "^1.7.2",
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.15",
    "@types/node": "^18.11.17",
    "@types/passport": "^1.0.11",
    "@types/passport-azure-ad": "^4.3.1",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "@typescript-eslint/parser": "^5.47.0",
    "eslint": "^8.23.1",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "prettier": "^2.7.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.0.2"
  }
}
```

.github/workflows/deploy-dev.yml
```yml
name: Deploy Development

on:
  push:
    branches:
      - development

jobs:
  client:
    (omitted)

  server:
    runs-on: ubuntu-latest
    name: Deploy Server
    steps:
      - name: Pull Source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build And Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: polar-shuttle-management
          publish-profile: ${{ secrets.AZURE_WEB_APPS_PUBLISH_PROFILE_DEV }}
          package: ./server
```

![image](https://user-images.githubusercontent.com/13600696/236487948-142b4d8e-2477-4add-8a1c-68b5465bcf8c.png)

![image](https://user-images.githubusercontent.com/13600696/236487999-b3de9986-86d9-4d2b-a1a1-a92eedd1f046.png)

**Comment by NoCopy** [comment]
@Fish1 Take a look at https://github.com/npm/npm/issues/16861

**Comment by Fish1** [comment]
> @Fish1 Take a look at https://github.com/npm/npm/issues/16861

Will probably be able to take a deeper look on Monday. But if the solution is to upgrade npm, wouldnt that be in the control of this azure deployment script?

**Comment by NoCopy** [comment]
@Fish1 Oh, interesting. Looks like the Oryx Build is reusing the NPM cache. That looks like a bug in the Oryx build not this.

You can get around this by doing the build yourself before deploy

```
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm prune --production
          npm install
          npm run build:${{ github.ref_name }} --if-present
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ vars.PACKAGE_PATH }}
```
