### ISSUE TITLE
Can't Select Deployment Folder

### ISSUE THREAD

**Issue by p0onage** [Azure/webapps-deploy#34]
My repo has many projects inside and when I'm using GitHub actions it is deploying the entire repo to Azure. After looking into this I don't see a way we can set the default deployment folder but it is unusable to me unless I can achieve this

Thanks,
Joshua

**Comment by eaarora-ms** [comment]
Hi @p0onage  You can specify your folder or package using the following snippet:

`
name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: node-rn
        package: '$(System.DefaultWorkingDirectory)/_aabb'
`

Please let us know if this works for you.

**Comment by eaarora-ms** [comment]
`
- name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: node-rn
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
`

**Comment by eaarora-ms** [comment]
Hi @p0onage  You can specify your folder or package using the following snippet:

```
- name: 'Run Azure webapp deploy action'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: node-rn
        package: '$(System.DefaultWorkingDirectory)/_aabb'
```

Please let us know if this works for you.
