### ISSUE TITLE
startup-command parameter is ignored

### ISSUE THREAD

**Issue by guillaumemeyer** [Azure/webapps-deploy#37]
We're using this GitHub action to deploy an app to Azure App Services.
The workflows seems to works (and the deployment occurs) but the `startup-command` is ignored, and GitHub raises an error:

![image](https://user-images.githubusercontent.com/1385518/85077328-4ce3f100-b1c2-11ea-82ff-5224fda1f5e9.png)

This message contradicts the [yaml action definition file](https://github.com/Azure/webapps-deploy/blob/master/action.yml).

Here is our yaml action file:
```yaml
name: REDACTED
on:
  push:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v1
        with:
          app-name: "REDACTED"
          startup-command: "npm run api-prd"
          slot-name: "production"
          publish-profile: REDACTED
          package: .
```

Am I missing something or is it a known issue?

**Comment by aksm-ms** [comment]
startup-command input is not supported in v1. It is supported in v2. 
Please refer the inputs for v1 - https://github.com/Azure/webapps-deploy/blob/v1/action.yml

**Comment by guillaumemeyer** [comment]
Thanks @aksm-ms . I just upgraded to v2 and it works.

As a feedback, it's quite easy from this repo to find docs about v2 without realizing it (or maybe it's just me ;-) ).
For instance from this page, you have to notice then switch the tag:
![image](https://user-images.githubusercontent.com/1385518/86792185-86de3f80-c06a-11ea-80ea-b049f7646626.png)
Maybe including the version number as a comment directly in the `action.yml` would be helpful.

Also, what is the status of v2? Is it considered as production ready? Again, having this info from the README page would be great.

**Comment by guillaumemeyer** [comment]
Rectification, I now have this issue:
![image](https://user-images.githubusercontent.com/1385518/86793208-86927400-c06b-11ea-9cdd-4811f70476b9.png)
We're running on Linux container, so I think this issue is related to how we're managing publish-profile...
Is it useful to try with v2.1? Any documentation that would describe the differences?

**Comment by guillaumemeyer** [comment]
Same problem with v2.1

**Comment by suyash691** [comment]
+1 on this issue with v2
The line
```
 if (!!startupCommand) {
        throw new Error("startup-command is not a valid input for Windows web app or with publish-profile auth scheme.");
    }
```
This will always cause an exception to be thrown if startupcommand is present since this will evaluate to true with a non empty string

**Comment by aksm-ms** [comment]
> As a feedback, it's quite easy from this repo to find docs about v2 without realizing it (or maybe it's just me ;-) ).
> For instance from this page, you have to notice then switch the tag:
> ![image](https://user-images.githubusercontent.com/1385518/86792185-86de3f80-c06a-11ea-80ea-b049f7646626.png)
> Maybe including the version number as a comment directly in the `action.yml` would be helpful.

Can you please explain more here? I am unable to understand the exact problem.

**Comment by aksm-ms** [comment]
> Also, what is the status of v2? Is it considered as production ready? Again, having this info from the README page would be great.

v2 is production ready and released to marketplace.

**Comment by aksm-ms** [comment]
> Rectification, I now have this issue:
> ![image](https://user-images.githubusercontent.com/1385518/86793208-86927400-c06b-11ea-9cdd-4811f70476b9.png)
> We're running on Linux container, so I think this issue is related to how we're managing publish-profile...
> Is it useful to try with v2.1? Any documentation that would describe the differences?

Please share the workflow for debugging.

**Comment by guillaumemeyer** [comment]
```yaml
name: REDACTED
on:
  push:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "REDACTED"
          startup-command: "npm run api-prd"
          slot-name: "production"
          publish-profile: REDACTED
          package: .
```
