### ISSUE TITLE
README doesn't have a v3 example or explanation of the differences

### ISSUE THREAD

**Issue by jsoref** [Azure/webapps-deploy#388]
All examples in README.md on the v3 branch as of now:
https://github.com/Azure/webapps-deploy/blob/145a0687697df1d8a28909569f6e5d86213041f9/README.md#L90
https://github.com/Azure/webapps-deploy/blob/145a0687697df1d8a28909569f6e5d86213041f9/README.md#L122
https://github.com/Azure/webapps-deploy/blob/145a0687697df1d8a28909569f6e5d86213041f9/README.md#L177

Some thoughts about the [3.0.0 release notes](https://github.com/Azure/webapps-deploy/releases/tag/v3.0.0):

### Features
> * Ex: `- type=war: Deploy a WAR package. By default, the WAR package is deployed to /home/site/wwwroot/app.war. The target path can be specified with parameter target-path.`

-- it's unlikely this is formatted correctly.

> Allowed values: `true/false`

should be written as:
> Allowed values: `true`/`false`

### Example

```yaml
- name: Deploy to Azure Web App
  id: deploy-to-webapp
  uses: azure/webapps-deploy@v3
  with:
    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: '*.war'
    type: (jar, war, zip, static)
    clean: (true, false)
    target-path: (i.e. /home/site/wwwroot/test, /home/site/wwwroot/test.war)
    restart: (true, false)
```

This example kinda relates to the original point -- something like this should be present in the readme. Ideally with a sample of a `v2` workflow and an equivalent `v3` workflow.
