### ISSUE TITLE
Can't deploy to ACA-based Function App

### ISSUE THREAD

**Issue by bc3tech** [Azure/webapps-deploy#405]
Using the following YAML

```yaml
    - name: 'Sign in via Azure CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: xxx.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        pushd xxx.sh
        docker build -q -t $container_image .
        docker push -q $container_image
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'xxx'
        images: $container_image
```

which maps directly to the docs [here](https://github.com/Azure/webapps-deploy#sample-workflow-to-build-and-deploy-a-nodejs-app-to-containerized-webapp-using-azure-service-principal), 

I get the following error during deployment:

![image](https://github.com/Azure/webapps-deploy/assets/1967433/58e2ad61-5810-415e-a97b-f39c97cfd022)
