### ISSUE TITLE
Deployment Failed, Error: No credentials found

### ISSUE THREAD

**Issue by rufer7** [Azure/webapps-deploy#445]
For some not yet identified reason, the `azure/webapps-deploy@v3` (I also tried `azure/webapps-deploy@v3.0.2`) fails with the following error:

```
Error: Deployment Failed, Error: No credentials found. Add an Azure login action before this action. For more details refer https://github.com/azure/login
```

My GitHub actions workflow job looks as follows:

```yml
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment: dev
    needs: [build_test_publish, iac_apply]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3.0.2
        with:
          app-name: my-app
          package: .
      - name: Logout
        run: |
          az logout
```

The steps `Download artifact` and `azure/login@v2` both succeed. To set up the secrets, I followed the official docs [here](https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=openid%2Caspnetcore#set-up-a-github-actions-workflow-manually) and the jobs before the one above succeed with the same secrets (iac_apply for example). I also enabled debug logging where I saw that `az account show` is executed and the next log entry was `{}` so I assume the account show command returns an empty object. But I have no idea why. Would be happy about any suggestions, hints or resolutions.
