### ISSUE TITLE
Someone just broke the 2.1

### ISSUE THREAD

**Issue by terrajobst** [Azure/webapps-deploy#48]
My workflow did this successfully yesterday night:

```yaml
    - name: Deploy ApiReview.Client
      uses: azure/webapps-deploy@v2.1
      with: 
        app-name: apireviews
        package: './artifacts/ApiReview.Client'
```

which fails with this:

```text
An action could not be found at the URI 'https://api.github.com/repos/azure/webapps-deploy/tarball/v2.1'
```

hacking the URL reveals that this works:

https://codeload.github.com/Azure/webapps-deploy/legacy.tar.gz/v2.1.0

Is that intentional?
