### ISSUE TITLE
Container deployment to app service deployment slot not working

### ISSUE THREAD

**Issue by bowdenk7** [Azure/webapps-deploy#52]
I have an app service `frosted-web` with a deployment slot `staging`.

![image](https://user-images.githubusercontent.com/820883/88239509-38c06300-cc4a-11ea-8a04-c04dbaa956de.png)

I use the following `azure/webapps-deploy@v2` action to try to push a new image to the `staging` slot on the `frosted-web` app service.

```
        - name: Update image tag on the staging Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'frosted-web'
            slot-name: 'staging'
            images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/frosted-web:${{ github.sha }}'
```

However I get the following error:
![image](https://user-images.githubusercontent.com/820883/88239627-89d05700-cc4a-11ea-9d4a-0888eaf2db08.png)

I can't seem to find any docs on how to use `slot-name`, but I would've expected this to just work. Deploying to the production slot works just fine. Am I missing something here?
