### ISSUE TITLE
Application deployment to staging slot

### ISSUE THREAD

**Issue by modev** [Azure/webapps-deploy#56]
I'm sorry if this is not the right place to report this issue, feel free to direct me elsewhere.

I'm currently working on a test application to evaluate the capabilities of GH Actions and the Azure AppService. I've been using the default node.js example and built upon that. Deploying the the production slot of my App Service worked without any issues. However, my issue is the deployment to other deployment slots such as staging.

Currently, there is no mention of the "slot-name" property in the documentation other than #25. Since official documentation is lacking I referred to the issue when formatting my configuration which now looks like this 
```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: 'Checkut Code'
      uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-app'
        publish-profile: ${{ secrets.AZURE_PUBLISHING_PROFILE }}
        slot-name: 'staging'
```
I generated the publishing profile using the "Generate publish profile" on the panel, but using the azure cli with the --xml flag produces the same output. I also manually created the deployment slot using the panel.

Executing the workflow with the configuration shown above results in the following error:

> ##[error]Deployment Failed with Error: Error: Publish profile is invalid for app-name and slot-name provided. Provide correct publish profile credentials for app.

wich appears to be caused by failing the validation here

https://github.com/Azure/webapps-deploy/blob/e985d6f66d42727d915c98d12585d59f9e15dbb3/src/ActionInputValidator/Validations.ts#L25-L38

I followed [this document](https://docs.microsoft.com/de-de/azure/app-service/deploy-github-actions) for general setup of my workflow.

Were there any breaking changes that resulted in the documentation being outdated?
