### ISSUE TITLE
Mapping volumes

### ISSUE THREAD

**Issue by ashokgelal** [Azure/webapps-deploy#63]
How does one go about mapping volumes? I want to map to a an Azure File Storage. Basically, what I'm looking is being able to do something like this (if it was a docker-compose.yml file):

```yml
services:
    ...
    ...
    volumes:
      - data:/var/www/html
```

Where `data` is the name of my Azure Storage mount name. Thank you!
