### ISSUE TITLE
Error: Invalid entry header

### ISSUE THREAD

**Issue by pblanchardie** [Azure/webapps-deploy#76]
Using v2 or v1, I'm unable to deploy a Spring Boot app (JHipster)

```
Error: Deployment Failed with Error: Error: Invalid entry header
Error: Error: Invalid entry header
```

```
-   name: Deploy to Azure WebApp
     uses: azure/webapps-deploy@v2
     with:
          app-name: _my-app-name_
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}/target/*jar'
```
