### ISSUE TITLE
Add support deployment to App Serivce kind of functionapp

### ISSUE THREAD

**Issue by shibayan** [Azure/webapps-deploy#77]
I get an error deploying Azure Functions if I am using RBAC. This does not occur if you are using an issue profile.

>Run azure/webapps-deploy@v2 Error: Deployment Failed with Error: Error: Action does not support app service with kind functionapp.

I know there is an `Azure/functions-action`, but it would be redundant to not be able to use the same Action when deploying in parallel using strategy.

**Comment by aksm-ms** [comment]
@N-Usha please take a look at this

**Comment by N-Usha** [comment]
@shibayan  - Could you plz elaborate your scenario further? I couldnt quite understand what you meant by below: Can you plz explain?

> but it would be redundant to not be able to use the same Action when deploying in parallel using strategy.

**Comment by shibayan** [comment]
@N-Usha I understand. I'll show you the actual Workflow definition.

Deploying to App Service / Azure Functions is often time consuming, so I use artifacts to deploy in parallel if the project contains many applications.

- webapp-test
  - App Service, ASP.NET Core application
- function-test
  - Azure Functions app

Currently, I simply define multiple jobs to deploy in parallel, but they are redundant as they are nearly identical except for the application name.

```yaml
# for webapp
deploy-webapp:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v2
    with:
      name: webapp-test
      path: publish

  - name: Login to Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: Deploy
    uses: Azure/webapps-deploy@v2
    with:
      app-name: webapp-test
      package: publish

# for function
deploy-function:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v2
    with:
      name: function-test
      path: publish

  - name: Login to Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: Deploy
    uses: Azure/functions-action@v1
    with:
      app-name: function-test
      package: publish
```

Therefore, I am thinking of reusing Job of deployment using strategy and matrix as follows.

But it is inconvenient that `webapps-deploy` action needs to be prepared separately with Web App and Function because deployment to Azure Functions cannot be done in Azure CLI mode.

```yaml
# deploy all application at once
deploy-all:
  runs-on: ubuntu-latest
  needs: build
  strategy:
    matrix:
      app: [webapp-test, function-test]
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v2
    with:
      name: ${{ matrix.app }}
      path: publish

  - name: Login to Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: Deploy to Dev
    uses: Azure/webapps-deploy@v2
    with:
      app-name: ${{ matrix.app }}
      package: publish
```

This workflow actually fails with an error when deploying to Azure Functions.
