### ISSUE TITLE
Inconsistent "Error: Deployment Failed with Error: Error: Action does not support app service with kind linux,container."

### ISSUE THREAD

**Issue by brookpatten** [Azure/webapps-deploy#83]
I have a workflow that I use to deploy to 2 different app services for containers.

To the best of my ability, they are identical other than the environment variables passed to the container and the subscriptions they are in.  I can configure both in azure portal and start the docker container manually in both, no problem.

Both are deployed to azure "app service environments" for my client.  They are under 2 different subscriptions, thus I use 2 different credentials to log in depending on which one I'm deploying.

The workflow contains steps like this

```
    - name: Login to Azure Non Prod
      uses: Azure/login@v1
      if: github.event.inputs.environment  != 'prod'
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Login to Azure Prod
      uses: Azure/login@v1
      if: github.event.inputs.environment  == 'prod'
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
    
    - name: Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: web-app-foo-${{ github.event.inputs.environment }}
        images: ghcr.io/client-name/image-name:tag
```

The problem, is that just one of them always errors with 
`Error: Deployment Failed with Error: Error: Action does not support app service with kind linux,container.`

What else can I look at in terms of properties of the app services or arguments passed to the action that would cause this to only fail for one?
