### ISSUE TITLE
Web App for Containers not actively pulling image after running azure/webapps-deploy@v2

### ISSUE THREAD

**Issue by Salazander** [Azure/webapps-deploy#99]
After triggering azure/webapps-deploy@v2, my instance of Web App for Containers does not actively pull the newest docker image hosted in GitHub Packages (docker.pkg.github.com). 

Workaround: Make a GET-request to the web app's URL - this seems to trigger the pending image retrieval.

**Comment by AmrutaKawade** [comment]
@Salazander  can you share your workflow yaml?

**Comment by Salazander** [comment]
@AmrutaKawade 
Here is a redacted version of my workflow (none of the paths make sense obviously):

```
name: 'Deploy XXX to Azure'

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish docker images"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy-to-azure-app-service:
    runs-on: ubuntu-latest    

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     
    steps:
      - name: 'Checkout the repo' 
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: 'Terraform Init'
        run: terraform init -backend-config=xxx-yyy.tfvars
        working-directory: ./terraform/dev

      - name: 'Set AppService Name as ENV variable'
        run: echo "APP_SERVICE_NAME=$(terraform output appservice_xx_name | tr -d '"')" >> $GITHUB_ENV
        working-directory: ./terraform/dev

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: "{\"clientId\":\"${{ secrets.AZURE_CLIENT_ID }}\",\"clientSecret\":\"${{ secrets.AZURE_CLIENT_SECRET }}\",\"subscriptionId\":\"${{ secrets.AZURE_SUBSCRIPTION_ID }}\",\"tenantId\":\"${{ secrets.AZURE_TENANT_ID }}\" }"   
                 
      - name: 'Deploy the XXX-WebApp' 
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: 'docker.pkg.github.com/xxx/yyy/zzz:latest'
        
      - name: 'Kickstart the XXX-WebApp'
        run: curl "https://${{ env.APP_SERVICE_NAME }}.azurewebsites.net"



```
